{ authors }:

with authors; [
  { author = SEbbaDK; image = ./the-declarative-trinity.webp; }
  { author = binaryplease; image = ./my-nixos-setup.png; }
  { author = chunkypuffs; image = ./before-and-after-nix.png; }
  { author = chunkypuffs; image = ./hard-to-swallow-pills.png; }
  { author = chunkypuffs; image = ./i-hate-docker.webp; }
  { author = chunkypuffs; image = ./just-try-the-goddam-nix.webp; }
  { author = chunkypuffs; image = ./nix-learning-curve.png; }
  { author = chunkypuffs; image = ./nix-vs-gentoo.png; }
  { author = chunkypuffs; image = ./nixos-deploy.png; }
  { author = chunkypuffs; image = ./no-going-back.png; }
  { author = chunkypuffs; image = ./random-repos.png; }
  { author = chunkypuffs; image = ./whats-the-difference.webp; }
  { author = cirkku; image = ./nixos-dominos.png; }
  { author = dramforever; image = ./nix-path-supports-urls.jpg; }
  { author = dramforever; image = ./virtualbox-starts-compiling.jpg; }
  { author = makefu; image = ./stop-using-nixos.webp; }
  { author = matthewcroughan; image = ./config-not-entierly-declarative.png; }
  { author = matthewcroughan; image = ./debian-and-arch-bad.png; }
  { author = matthewcroughan; image = ./do-not-get-mad.png; }
  { author = matthewcroughan; image = ./eelco-nixpill.png; }
  { author = matthewcroughan; image = ./eelco-prism.apng; }
  { author = matthewcroughan; image = ./fleyks.png; }
  { author = matthewcroughan; image = ./mobile-nixos.png; }
  { author = matthewcroughan; image = ./who-would-win.png; }
  { author = mlvzk; image = ./nixos-shilling.png; }
  { author = mlvzk; image = ./techy-kid.png; }
  { author = nixinator; image = ./nix-vs-fhs.png; }
  { author = pily; image = ./quick-install-nixos.webp; }
  { author = r2r-dev; image = ./homer-nix-bush.gif; }
  { author = synthetica; image = ./superiority-complex.png; }
  { author = unknown; image = ./nix-programming-socks.png; }
  { author = unknown; image = ./pinnacle-of-system-configuration.png; }
  { author = unknown; image = ./thank-you-for-changing-my-life.png; }
  { author = unknown; image = ./virgin-arch-vs-chad-nixos.png; }
  { author = unknown; image = ./heaviest-objects-in-the-universe.png; }
  { author = unrooted; image = ./nagatoro-nix-pervert.png; }
  { author = unrooted; image = ./nix-20min-adventure.png; }
  { author = unrooted; image = ./nixenv-vs-nixshell.png; }
  { author = unrooted; image = ./org-vs-com.png; }
  { author = unknown; image = ./hermetic-tooling.jpg; }
  { author = makefu; image = ./nixos-at-home.jpg; }
  { author = makefu; image = ./aarch64-joke.jpg; }
  { author = makefu; image = ./dark-secret-nixpkgs.png; }
  { author = makefu; image = ./electron.jpg; }
  { author = makefu; image = ./pr-open.jpg; }
  { author = makefu; image = ./stay-on-freenode.jpg; }
  { author = matthewcroughan; image = ./they-dont-know-im-reproducible.png; }
  { author = djacu; image = ./nix-god.jpg; }
  { author = djacu; image = ./flake-magic.png; }
  { author = bbjubjub; image = ./averagenixfan.png; }
  { author = davidnuon; image = ./legend-of-nixos.png; }
  { author = typecraft; image = ./nixos-fixes-this.jpg; }
  { author = djacu; image = ./nix-expression-language-armor.jpeg; }
  { author = unknown; image = ./nixmms-004.jpg; }
  { author = JustNerfRaze; image = ./nixmms-007.jpg; }
  { author = unknown; image = ./nixmms-009.jpg; }
  { author = unknown; image = ./nixmms-019.jpg; }
  { author = unknown; image = ./nixmms-020.jpg; }
  { author = sophronesis; image = ./nixmms-052.jpg; }
  { author = sophronesis; image = ./nixmms-056.jpg; }
  { author = sophronesis; image = ./nixmms-060.jpg; }
  { author = unknown; image = ./nixmms-084.jpg; }
  { author = unknown; image = ./nixmms-085.jpg; }
  { author = unknown; image = ./nixmms-107.jpg; }
  { author = unknown; image = ./nixmms-112.jpg; }
  { author = unknown; image = ./nixmms-118.jpg; }
  { author = unknown; image = ./nixmms-119.jpg; }
  { author = sophronesis; image = ./nixmms-123.jpg; }
  { author = unknown; image = ./nixmms-125.jpg; }
  { author = unknown; image = ./nixmms-126.jpg; }
  { author = unknown; image = ./nixmms-207.jpg; }
  { author = femsci; image = ./nixmms-221.jpg; }
  { author = unknown; image = ./nixmms-240.jpg; }
  { author = unknown; image = ./nixmms-262.jpg; }
  { author = unknown; image = ./nixmms-325.jpg; }
  { author = unknown; image = ./nixmms-335.jpg; }
  { author = unknown; image = ./nixmms-354.jpg; }
  { author = unknown; image = ./nixmms-366.jpg; }
  { author = unknown; image = ./nixmms-411.jpg; }
  { author = baer; image = ./nixmms-418.jpg; }
  { author = unknown; image = ./nixmms-432.jpg; }
  { author = unknown; image = ./nixmms-437.jpg; }
  { author = unknown; image = ./nixmms-439.jpg; }
  { author = unknown; image = ./nixmms-441.jpg; }
  { author = unknown; image = ./nixmms-472.jpg; }
]
